/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Interfaces.IProducto;
import java.rmi.RemoteException;

/**
 *
 * @author Yanglee DM
 */
public class DialogModificarProducto extends javax.swing.JDialog {

    /**
     * Creates new form DialogModificarProducto
     */
    public DialogModificarProducto(java.awt.Frame parent, boolean modal, IProducto producto) throws RemoteException {
        super(parent, modal);
        initComponents();
        setSize(480, 300);
        
        getContentPane().add(new PanelModificarProducto(this, producto));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
