/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Interfaces.IVenta;
import java.rmi.RemoteException;

/**
 *
 * @author Yanglee DM
 */
public class DialogModificarVenta extends javax.swing.JDialog {


    
    public DialogModificarVenta(java.awt.Frame parent, boolean modal, IVenta venta) throws RemoteException {
        super(parent, modal);
        
        initComponents();
        setSize(480, 300);
        
        this.getContentPane().add(new PanelModificarVenta(this, venta));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        pack();
    }// </editor-fold>//GEN-END:initComponents




    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
