/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import Interfaces.IProducto;
import Interfaces.IVenta;
import Interfaces.IVentaController;
import java.rmi.RemoteException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import proyectofinalpinocliente.RMIVenta;

/**
 *
 * @author Yanglee DM
 */
public class PanelAgregarVenta extends javax.swing.JPanel {

    /**
     * Creates new form PanelAgregarVenta
     */
    private JDialog dialogParent;

    public PanelAgregarVenta(JDialog dialogParent) {
        initComponents();
        idProductoTextField.setEnabled(false);
        this.dialogParent = dialogParent;
        
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        estadoCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        montoTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fechaTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        idProductoTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        aceptarButton = new javax.swing.JButton();
        exitButton = new javax.swing.JLabel();
        verProductosButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 51));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Proporciona el estado de la venta");

        estadoCheckBox.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        estadoCheckBox.setForeground(new java.awt.Color(204, 204, 204));
        estadoCheckBox.setText("Aprobada");
        estadoCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoCheckBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agregar venta");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Monto de la venta");

        montoTextField.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingresa la fecha de la venta");

        jButton1.setFont(new java.awt.Font("Bahnschrift", 1, 11)); // NOI18N
        jButton1.setText("HOY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingresa el producto de la venta");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/sell.png"))); // NOI18N

        aceptarButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        aceptarButton.setText("Aceptar");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(255, 0, 51));
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/close.png"))); // NOI18N
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });

        verProductosButton.setFont(new java.awt.Font("Bahnschrift", 1, 11)); // NOI18N
        verProductosButton.setText("Ver productos");
        verProductosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verProductosButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fechaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(montoTextField)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idProductoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(verProductosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(estadoCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aceptarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 5, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(montoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fechaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idProductoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verProductosButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estadoCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(aceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked

        int confirmacion = JOptionPane.showConfirmDialog(this, "Está seguro de cancelar esta operación?", "Advertencia", JOptionPane.YES_NO_OPTION);

        if(confirmacion == JOptionPane.YES_OPTION){
            dialogParent.setVisible(false);
        }else{
            return;
        }
    }//GEN-LAST:event_exitButtonMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
        Date miFecha = new Date();

            //Formato de fecha
        
            SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
            String fecha = formatoFecha.format(miFecha);
            
            fechaTextField.setText(fecha);
            fechaTextField.setEnabled(false);
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void verProductosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verProductosButtonActionPerformed
        
        
        DialogVerProductos dialogVerProductos = new DialogVerProductos(null, true);

        dialogVerProductos.setLocationRelativeTo(this);
        dialogVerProductos.setVisible(true);
        
        ProductoVentaProperties idClase = new ProductoVentaProperties();

        
        idProductoTextField.setText(idClase.getProductoID());
        
        montoTextField.setText(idClase.getPrecioProducto());
        
    }//GEN-LAST:event_verProductosButtonActionPerformed

    private void estadoCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoCheckBoxActionPerformed
        

        
    }//GEN-LAST:event_estadoCheckBoxActionPerformed

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed

        
        try {
            String fecha = fechaTextField.getText();
            String monto = montoTextField.getText();
            String estado = "";
            if(estadoCheckBox.isSelected()){
                estado = "Aprobada";
            }else{
                
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Desea especificar el estado de la venta?", "Advertencia", JOptionPane.YES_NO_OPTION);

            if(confirmacion == JOptionPane.YES_OPTION){
                return;
            }else{
                estadoCheckBox.setSelected(true);
                estadoCheckBox.setEnabled(false);
                estadoCheckBox.setText("En proceso");
                estado = "En proceso";
            }
            
            }
            
            
            
            IVenta venta = RMIVenta.getIVentaController().newInstance();
            
            if (monto.length() > 0){
                venta.setPrecioVenta(Integer.parseInt(monto));
            }else{
                JOptionPane.showMessageDialog(
                        this, 
                        "Por favor ingrese un monto valido",
                        "Validación",
                        JOptionPane.ERROR_MESSAGE);
                montoTextField.requestFocus();
            }
            if(fechaTextField.getText().length() == 0){
                JOptionPane.showMessageDialog(
                        this, 
                        "Por favor ingrese la fecha de la venta",
                        "Validación",
                        JOptionPane.ERROR_MESSAGE);
                fechaTextField.requestFocus();
            }
            
            if (idProductoTextField.getText().length() == 0){
                JOptionPane.showMessageDialog(
                        this, 
                        "Por favor ingrese un id válido",
                        "Validación",
                        JOptionPane.ERROR_MESSAGE);
                idProductoTextField.requestFocus();
            }else{
                
                int idProducto = Integer.parseInt(idProductoTextField.getText());
                venta.setIdProducto(idProducto);
            }
            
            
            
            venta.setEstadoVenta(estado);
            venta.setFechaVenta(fecha);
            
            
            
            
            int respuesta = RMIVenta.getIVentaController().add(venta);
            
            if(respuesta == IVentaController.ADD_EXITO){
                JOptionPane.showMessageDialog(this,
                        "Venta añadida exitosamente",
                        "Aviso",
                        JOptionPane.INFORMATION_MESSAGE);
                dialogParent.dispose();
                
            }else if(respuesta == IVentaController.ADD_SIN_EXITO){
                JOptionPane.showMessageDialog(this,
                        "Ocurrió un error al añadir la venta",
                        "Operación interrumpida",
                        JOptionPane.ERROR_MESSAGE);
            }
            
            
           
            
            
        } catch (RemoteException ex) {
            Logger.getLogger(PanelAgregarVenta.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        
    }//GEN-LAST:event_aceptarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JCheckBox estadoCheckBox;
    private javax.swing.JLabel exitButton;
    private javax.swing.JTextField fechaTextField;
    private javax.swing.JTextField idProductoTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField montoTextField;
    private javax.swing.JButton verProductosButton;
    // End of variables declaration//GEN-END:variables
}
