/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Interfaces.IProducto;
import Interfaces.IProductoController;
import java.awt.BorderLayout;
import java.rmi.RemoteException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import proyectofinalpinocliente.RMI;

/**
 *
 * @author Yanglee DM
 */
public class VerProductos extends javax.swing.JPanel {
    public Inicio inicio;
    private static String ID = "ID";
    private static String NOMBRE = "Nombre";
    
    
    
    public VerProductos() {
        initComponents();
        refrescarTabla();
    }
    
    public void refrescarTabla(){
        try { 
            
            Vector<Vector> datos = new Vector(); // Dónde van datos
            String textoBuscar = buscarTextField.getText(); //Recucperando texto que se va buscar
            
            List<IProducto> listProducto; //Donde quedan asignadas todas o un fragmento
            if(textoBuscar.length() == 0 ){ // Si tiene texto o no
                
                listProducto = RMI.getIProductoController().list(); //Si no tiene texto, recuperamos a todos
                
            }else{ //CONSULTA
                IProducto producto = RMI.getIProductoController().newInstance();
                
                String columna = columnasComboBox.getSelectedItem().toString();
                
                if(columna.compareTo(ID) == 0){
                    try{
                    producto.setIdProducto(Integer.parseInt(textoBuscar));
                    }catch(NumberFormatException ex){
                        JOptionPane.showMessageDialog(this, "Se requiere un valor númerico", "Número requerido",
                        JOptionPane.ERROR_MESSAGE
                        );
                        
                        return;
                    }
                }else if(columna.compareTo(NOMBRE) == 0){
                    producto.setNombreProducto(textoBuscar);
                }
                
                listProducto = RMI.getIProductoController().find(producto);
            }
            
            
            for (IProducto producto : listProducto){
                Vector registro = new Vector();
                registro.add(producto.getIdProducto());
                registro.add(producto.getNombreProducto());
                registro.add(producto.getPrecioProducto());
                registro.add(producto.getDescripProducto());
                registro.add(producto.getFechaIngreso());
                registro.add(producto.getCantidad());
                
                
                
                datos.add(registro);
            }
            
            
            Vector<String> columnas = new Vector();
            
            columnas.add("Identificador");
            columnas.add("Nombre");
            columnas.add("Precio");
            columnas.add("Descripción");
            columnas.add("Fecha de ingreso");
            columnas.add("Cantidad");
            personasTable.setModel(new DefaultTableModel(datos, columnas));
            TableColumnModel columnModel = personasTable.getColumnModel();
            columnModel.getColumn(0).setPreferredWidth(0);
            
        } catch (RemoteException ex) {
            Logger.getLogger(VerProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        personasTable = new javax.swing.JTable();
        columnasComboBox = new javax.swing.JComboBox();
        buscarTextField = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        agregarButton = new javax.swing.JButton();
        modificarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        actualizarButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        exitButton.setBackground(new java.awt.Color(255, 0, 51));
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/close.png"))); // NOI18N
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });

        personasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        personasTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jScrollPane1.setViewportView(personasTable);

        columnasComboBox.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        columnasComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nombre", " " }));

        buscarButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Productos");

        agregarButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        agregarButton.setText("Agregar");
        agregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButtonActionPerformed(evt);
            }
        });

        modificarButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        modificarButton.setText("Modificar");
        modificarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarButtonActionPerformed(evt);
            }
        });

        eliminarButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        actualizarButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        actualizarButton.setText("Actualizar");
        actualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarButtonActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logout.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cafe65.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("La montaña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(agregarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modificarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(actualizarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(columnasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(columnasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(agregarButton)
                        .addGap(18, 18, 18)
                        .addComponent(modificarButton)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarButton)
                        .addGap(18, 18, 18)
                        .addComponent(actualizarButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked

        System.exit(0);
    }//GEN-LAST:event_exitButtonMouseClicked

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
    refrescarTabla();
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed
        
        
        DialogAgregarProducto dialogAgregarProducto = new DialogAgregarProducto(null, true);
        
        dialogAgregarProducto.setLocationRelativeTo(this);
        dialogAgregarProducto.setVisible(true);
        refrescarTabla();
        
       
        
        
        
        
    }//GEN-LAST:event_agregarButtonActionPerformed

    private void modificarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarButtonActionPerformed
        

        
        try {
            int filaSeleccionada = personasTable.getSelectedRow();
            if (filaSeleccionada == -1){
                JOptionPane.showMessageDialog(
                        this,
                        "Por favor selecciona un registro para modificar",
                        "Error: Registro no seleccionado",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            int idProducto = (Integer) personasTable.getValueAt(filaSeleccionada, 0);
            IProducto producto = RMI.getIProductoController().findOne(idProducto);
            
            if(producto.getIdProducto()== 0){
                
                JOptionPane.showMessageDialog(
                        this,
                        "Es probable que el producto haya sido eliminada previamente",
                        "Error: Persona no encontrada",
                        JOptionPane.ERROR_MESSAGE);
                refrescarTabla();
            return;
            }
            
            
        DialogModificarProducto dialogModificarProducto = new DialogModificarProducto(null, true, producto);
        
        dialogModificarProducto.setLocationRelativeTo(this);
        dialogModificarProducto.setVisible(true);
        
        refrescarTabla();

            
            
        } catch (RemoteException ex) {
            Logger.getLogger(VerProductos.class.getName()).log(Level.SEVERE, null, ex);
        }        
        
        
    }//GEN-LAST:event_modificarButtonActionPerformed

    private void actualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarButtonActionPerformed
        refrescarTabla();
        
    }//GEN-LAST:event_actualizarButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        try {
            int filaSeleccionada = personasTable.getSelectedRow();
            if (filaSeleccionada == -1){
                JOptionPane.showMessageDialog(
                        this,
                        "Por favor selecciona un registro para eliminar",
                        "Error: Registro no seleccionado",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar este registro?", "Advertencia", JOptionPane.YES_NO_OPTION);
            
            if(confirmacion != JOptionPane.YES_OPTION){
                return;
            }
            
            int idProducto = (Integer) personasTable.getValueAt(filaSeleccionada, 0);
            
            int respuesta = RMI.getIProductoController().delete(idProducto);
            
            if (respuesta == IProductoController.DELETE_EXITO){
                JOptionPane.showMessageDialog(this,
                        "Producto eliminado con éxito",
                        "Operación exitosa",
                        JOptionPane.INFORMATION_MESSAGE);
                refrescarTabla();
            }else if(respuesta == IProductoController.DELETE_ID_INEXISTENTE){
                JOptionPane.showMessageDialog(this,
                        "Producto no encontrada\n"+
                                "Es posible que el producto haya sido eliminada previamente",
                        "Persona no encontrada",
                        JOptionPane.ERROR_MESSAGE); 
            }else{
                JOptionPane.showMessageDialog(this,
                        "Operación incompleta",
                        "Ocurrió un error",
                        JOptionPane.ERROR_MESSAGE); 
            }
            
        } catch (RemoteException ex) {
            Logger.getLogger(VerProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        
        setVisible(false);
        inicio = new Inicio();
        removeAll();
        setLayout(new BorderLayout());
        setVisible(true);
        
        add(inicio);

        
        
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarButton;
    private javax.swing.JButton agregarButton;
    private javax.swing.JButton buscarButton;
    private javax.swing.JTextField buscarTextField;
    private javax.swing.JComboBox columnasComboBox;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JLabel exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarButton;
    private javax.swing.JTable personasTable;
    // End of variables declaration//GEN-END:variables
}
